### ISSUE TITLE
package error

### ISSUE THREAD

**Issue by j-v-As** [whchien/funda-scraper#21]
![image](https://github.com/whchien/funda-scraper/assets/144106721/90ece53e-d855-4005-853e-7edebbc497c7)

I used the scraper two days ago, and it worked fine, but now it doesn't return anything. Is this issue specific to my machine, or are others also experiencing this problem?

**Comment by coskoutelis** [comment]
I am having indeed the same issue

**Comment by coskoutelis** [comment]
The weird thing is that `raw_df` does have data, it's only the `clean_df` that is empty

**Comment by whchien** [comment]
hi @j-v-As @coskoutelis 

Funda updated its website layout this week. Users must log in to see the 'listed_since', contributing to this error. Therefore, I have to remove the downstream columns such as date_list, ym_list, and year_list to make the scraper run, unfortunately. 

This bug should be fixed in the latest release (v1.0.10). Please let me know if you encounter any problems.
